# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
    - osx
    - linux
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl; else sudo apt-get install libgsl0-dev; fi
warnings_are_errors: false
 
